services:
  - type: web
    name: safefind
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app_simple:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
